// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOrJeDTPGVyrWl_S0kWWeJCdxfBJ2C53c',
    appId: '1:1028490463027:web:0075bcf4d0a083faff6046',
    messagingSenderId: '1028490463027',
    projectId: 'promptu-7b099',
    authDomain: 'promptu-7b099.firebaseapp.com',
    storageBucket: 'promptu-7b099.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj00vXGVNrP4aQtmIAe3xv2nXUdM7HtRE',
    appId: '1:1028490463027:android:7e8ddc053b24e8fbff6046',
    messagingSenderId: '1028490463027',
    projectId: 'promptu-7b099',
    storageBucket: 'promptu-7b099.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7-QNMOVe3IHGqEJwL2PilEkWwUN_WmEQ',
    appId: '1:1028490463027:ios:d6bfed9bad3bc943ff6046',
    messagingSenderId: '1028490463027',
    projectId: 'promptu-7b099',
    storageBucket: 'promptu-7b099.firebasestorage.app',
    iosBundleId: 'com.example.promptu',
  );
}
